### ISSUE TITLE
[Feature Request] Mod list

### ISSUE THREAD

**Issue by eternalphane** [wormzjl/Fabrica-Atlantica#1]
I found this modpack interesting while searching for some zenscript examples on github. However I can't find any resource on 百度 (I saw `i18n_update_mod.cfg` in `/config` and assumed that you are a Chinese). Could you please add the list of mods to `README.md`?

**Comment by wormzjl** [comment]
懒（。

**Comment by wormzjl** [comment]
等发布再说吧（

**Comment by eternalphane** [comment]
> 懒（。

老哥您也太秀了吧...つ﹏⊂
